---
name: silverstripe-alert-banner
---

PageController:
  extensions:
    - DNADesign\AlertBanner\ControllerExtension

SilverStripe\Control\Director:
  rules:
    'alerts': 'DNADesign\AlertBanner\AlertBannerController'
